export const regex = {
   CPFRegEX: /(CPF: [0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{2})|(cpf: [0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{2})/g,
   processNumberRegex: /([0-9]{7}[\-]?[0-9]{2}[\.]?[0-9]{4}[\.]?[0-9]{1}[\.]?[0-9]{2}[\.]?[0-9]{4}?[A-Z])/g,
   nameRegex: /([\(][A-Z](.*) \W)/g,
   dateRegex: /([0-9]{2}[\/]?[0-9]{2}[\/]?[0-9]{4})/g,
   articleRegex: /([\(]Art|ART[\.])/g,
   dipRegex: /(DIP)/g,
   cpfRemoveRegex: /(CPF)/g,
   dibRegex: /(DIB)/g,
   nbRegex: /(NB)/g,
   reRegex: /(RE [0-9])/g,
   ecRegex: /(EC )/g,
   derRegex: /(DER)/g,
   doRegex: /(DO [\-])/g,
   dcbRegex: /(DCB)/g,
   doAteMesRegex: /(até)/g,
   idosoRegex: /(idoso|Idoso|IDOSO)/g,
   loasRegex: /(LOAS)/g,
   seisRegex: /(SEIS)/g,
   cincoRegex: /(CINCO)/g,
   videRegex: /(VIDE)/g,
   urbanoRegex: /(URBANO)/g,
   laudosRegex: /(LAUDOS)/g,
   sumulaRegex: /(Súmula)/g,
}